title: "Hu's Technical Notebook"
email: samyhhu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    "This notebook is intended to capture Hu's weird thoughts in the technical dimension."
baseurl: "" 
url: "samyhhu.github.io" # "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: samyhhu 

# Build settings
markdown: kramdown
