title: "Hu's Tech Blog"
email: samyhhu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    "Notes"
baseurl: ""
url: "samyhhu.github.io" # "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username: samyhhu

# Build settings
markdown: kramdown
